### ISSUE TITLE
How to put text in clipboard?

### ISSUE THREAD

**Issue by qPCR4vir** [qPCR4vir/nana#23]

**Comment by beru** [comment]
I can copy the value of a textbox by pressing Ctrl+C keys.
Do you mention API?
nana library uses ```#include <nana/system/dataexch.hpp>```
Here is an excerpt code from ```text_editor.cpp```
```c++
void text_editor::copy() const
{
	nana::string str;
	if(_m_make_select_string(str))
		nana::system::dataexch().set(str);
}
```

**Comment by qPCR4vir** [comment]
Thank!
Yes. I know the "copy" from textbox.
But the lower level '''nana::system::dataexch().set(str);''' is a good hint.
I was thinking in copying to the clipboard selected rows from a listbox. Probably I can paste a .csv string in an excel sheet or a text editor, and this can be a simple alternative to implement .csv export from my tables.
'''cpp
void listbox::copy() const
{
    nana::string str{to_csv()};
        nana::system::dataexch().set(str);
}
'''

**Comment by qPCR4vir** [comment]
[Using the Clipboard](https://msdn.microsoft.com/en-us/library/windows/desktop/ms649016%28v=vs.85%29.aspx#_win32_Copying_Information_to_the_Clipboard)
[GlobalAlloc function](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366574%28v=vs.85%29.aspx)
[GlobalLock function](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366584%28v=vs.85%29.aspx)
[SetClipboardData function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms649051%28v=vs.85%29.aspx)
[Standard Clipboard Formats](https://msdn.microsoft.com/en-us/library/windows/desktop/ff729168%28v=vs.85%29.aspx)
[Clipboard Formats](https://msdn.microsoft.com/en-us/library/windows/desktop/ms649013%28v=vs.85%29.aspx#_win32_Registered_Clipboard_Formats)
[Synthesized Clipboard Formats](https://msdn.microsoft.com/en-us/library/windows/desktop/ms649013%28v=vs.85%29.aspx#_win32_Synthesized_Clipboard_Formats)

[]()
